name: 520K_BERT_GAT
dataset: NYT-520K

# sent
sent_encoder: BERT

# graph
graph_encoder: GAT
graph_emb: 220
graph_hid: 250
graph_out: 300
num_layers: 2
num_heads: 2

# framework
class_dim: 768
batch_size: 16
bag_size: 4
epoch: 50
lr: 2e-5

## COMMON
root: data
processed_data_dir: _processed_data
train: train.json
test: test.json
rel2id: rel2id.json
type2id: type2id.json
graph: constraint_graph.json
vec_dir: vec.txt
save_dir: ckpt
log_dir: results
val_iter: 1
dropout: 0.5
seed: 16051643
pos_dim: 5
max_length: 120
max_pos_length: 100
