name: 520K_PCNN_GAT
dataset: NYT-520K

# sent
sent_encoder: PCNN
hidden_size: 230
lambda: 18

# graph
graph_encoder: GAT
graph_emb: 100
graph_hid: 400
graph_out: 1250
num_layers: 2
num_heads: 2

# framework
class_dim: 900
batch_size: 160
epoch: 50
lr: 0.5

## COMMON
root: data
processed_data_dir: _processed_data
train: train.json
test: test.json
rel2id: rel2id.json
type2id: type2id.json
graph: constraint_graph.json
vec_dir: vec.txt
save_dir: ckpt
log_dir: results
val_iter: 1
dropout: 0.5
seed: 16051643
pos_dim: 5
max_length: 120
max_pos_length: 100
